# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "authmesh-app"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[env]
  NODE_ENV = "production"
  PORT = "5000"
  KEYCLOAK_URL = ""
  KEYCLOAK_REALM = "authmesh"
  KEYCLOAK_CLIENT_ID = "authmesh-app"

[secrets]
  # Set these secrets using: fly secrets set SECRET_NAME=value
  # KEYCLOAK_CLIENT_SECRET
  # SESSION_SECRET
  # DATABASE_URL (if using a database)

[deploy]
  release_command = "npm run db:push"

[[statics]]
  guest_path = "/app/dist/public"
  url_prefix = "/static/"
