# Fly.io deployment configuration for Auth247

app = "auth247"
primary_region = "ord"

[build]
  builder = "heroku/buildpacks:20"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/health"
  port = 8080
  timeout = "5s"
  type = "http"

[http_service.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Uncomment for production scaling
# [[vm]]
#   cpu_kind = "performance"
#   cpus = 2
#   memory_mb = 2048